<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="9" failures="0" skipped="0" tests="9" time="0.276" timestamp="2023-11-20T11:11:41.449323" hostname="erhan"><testcase classname="tests.unit.test_camera.test_Camera" name="test_constructor" time="0.143"><error message="failed on setup with &quot;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 45&#10;      def test_constructor(self):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21&#10;  @pytest.fixture(autouse=True)&#10;  def test_cases_shortcuts(request, app, patching):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16&#10;  @pytest.fixture()&#10;  def app(celery_app):&#10;E       fixture 'celery_app' not found&#10;&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db&#10;&gt;       use 'pytest --fixtures [testpath]' for help on them.&#10;&#10;/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16&quot;">file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 45
      def test_constructor(self):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21
  @pytest.fixture(autouse=True)
  def test_cases_shortcuts(request, app, patching):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16
  @pytest.fixture()
  def app(celery_app):
E       fixture 'celery_app' not found
&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db
&gt;       use 'pytest --fixtures [testpath]' for help on them.

/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16</error></testcase><testcase classname="tests.unit.test_camera.test_Camera" name="test_get_heartbeat" time="0.002"><error message="failed on setup with &quot;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 52&#10;      def test_get_heartbeat(self):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21&#10;  @pytest.fixture(autouse=True)&#10;  def test_cases_shortcuts(request, app, patching):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16&#10;  @pytest.fixture()&#10;  def app(celery_app):&#10;E       fixture 'celery_app' not found&#10;&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db&#10;&gt;       use 'pytest --fixtures [testpath]' for help on them.&#10;&#10;/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16&quot;">file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 52
      def test_get_heartbeat(self):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21
  @pytest.fixture(autouse=True)
  def test_cases_shortcuts(request, app, patching):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16
  @pytest.fixture()
  def app(celery_app):
E       fixture 'celery_app' not found
&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db
&gt;       use 'pytest --fixtures [testpath]' for help on them.

/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16</error></testcase><testcase classname="tests.unit.test_camera.test_Camera" name="test_handle_worker" time="0.002"><error message="failed on setup with &quot;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 67&#10;      def test_handle_worker(self):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21&#10;  @pytest.fixture(autouse=True)&#10;  def test_cases_shortcuts(request, app, patching):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16&#10;  @pytest.fixture()&#10;  def app(celery_app):&#10;E       fixture 'celery_app' not found&#10;&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db&#10;&gt;       use 'pytest --fixtures [testpath]' for help on them.&#10;&#10;/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16&quot;">file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 67
      def test_handle_worker(self):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21
  @pytest.fixture(autouse=True)
  def test_cases_shortcuts(request, app, patching):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16
  @pytest.fixture()
  def app(celery_app):
E       fixture 'celery_app' not found
&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db
&gt;       use 'pytest --fixtures [testpath]' for help on them.

/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16</error></testcase><testcase classname="tests.unit.test_camera.test_Camera" name="test_handle_task_received" time="0.001"><error message="failed on setup with &quot;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 82&#10;      def test_handle_task_received(self):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21&#10;  @pytest.fixture(autouse=True)&#10;  def test_cases_shortcuts(request, app, patching):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16&#10;  @pytest.fixture()&#10;  def app(celery_app):&#10;E       fixture 'celery_app' not found&#10;&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db&#10;&gt;       use 'pytest --fixtures [testpath]' for help on them.&#10;&#10;/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16&quot;">file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 82
      def test_handle_task_received(self):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21
  @pytest.fixture(autouse=True)
  def test_cases_shortcuts(request, app, patching):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16
  @pytest.fixture()
  def app(celery_app):
E       fixture 'celery_app' not found
&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db
&gt;       use 'pytest --fixtures [testpath]' for help on them.

/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16</error></testcase><testcase classname="tests.unit.test_camera.test_Camera" name="test_handle_task" time="0.002"><error message="failed on setup with &quot;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 98&#10;      def test_handle_task(self):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21&#10;  @pytest.fixture(autouse=True)&#10;  def test_cases_shortcuts(request, app, patching):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16&#10;  @pytest.fixture()&#10;  def app(celery_app):&#10;E       fixture 'celery_app' not found&#10;&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db&#10;&gt;       use 'pytest --fixtures [testpath]' for help on them.&#10;&#10;/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16&quot;">file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 98
      def test_handle_task(self):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21
  @pytest.fixture(autouse=True)
  def test_cases_shortcuts(request, app, patching):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16
  @pytest.fixture()
  def app(celery_app):
E       fixture 'celery_app' not found
&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db
&gt;       use 'pytest --fixtures [testpath]' for help on them.

/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16</error></testcase><testcase classname="tests.unit.test_camera.test_Camera" name="test_handle_task_timezone" time="0.002"><error message="failed on setup with &quot;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 125&#10;      def test_handle_task_timezone(self):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21&#10;  @pytest.fixture(autouse=True)&#10;  def test_cases_shortcuts(request, app, patching):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16&#10;  @pytest.fixture()&#10;  def app(celery_app):&#10;E       fixture 'celery_app' not found&#10;&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db&#10;&gt;       use 'pytest --fixtures [testpath]' for help on them.&#10;&#10;/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16&quot;">file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 125
      def test_handle_task_timezone(self):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21
  @pytest.fixture(autouse=True)
  def test_cases_shortcuts(request, app, patching):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16
  @pytest.fixture()
  def app(celery_app):
E       fixture 'celery_app' not found
&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db
&gt;       use 'pytest --fixtures [testpath]' for help on them.

/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16</error></testcase><testcase classname="tests.unit.test_camera.test_Camera" name="test_on_cleanup_expires" time="0.001"><error message="failed on setup with &quot;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 196&#10;      def test_on_cleanup_expires(self, dec=332000):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21&#10;  @pytest.fixture(autouse=True)&#10;  def test_cases_shortcuts(request, app, patching):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16&#10;  @pytest.fixture()&#10;  def app(celery_app):&#10;E       fixture 'celery_app' not found&#10;&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db&#10;&gt;       use 'pytest --fixtures [testpath]' for help on them.&#10;&#10;/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16&quot;">file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 196
      def test_on_cleanup_expires(self, dec=332000):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21
  @pytest.fixture(autouse=True)
  def test_cases_shortcuts(request, app, patching):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16
  @pytest.fixture()
  def app(celery_app):
E       fixture 'celery_app' not found
&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db
&gt;       use 'pytest --fixtures [testpath]' for help on them.

/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16</error></testcase><testcase classname="tests.unit.test_camera.test_Camera" name="test_on_cleanup_does_not_expire_new" time="0.001"><error message="failed on setup with &quot;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 199&#10;      def test_on_cleanup_does_not_expire_new(self, dec=0):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21&#10;  @pytest.fixture(autouse=True)&#10;  def test_cases_shortcuts(request, app, patching):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16&#10;  @pytest.fixture()&#10;  def app(celery_app):&#10;E       fixture 'celery_app' not found&#10;&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db&#10;&gt;       use 'pytest --fixtures [testpath]' for help on them.&#10;&#10;/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16&quot;">file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 199
      def test_on_cleanup_does_not_expire_new(self, dec=0):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21
  @pytest.fixture(autouse=True)
  def test_cases_shortcuts(request, app, patching):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16
  @pytest.fixture()
  def app(celery_app):
E       fixture 'celery_app' not found
&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db
&gt;       use 'pytest --fixtures [testpath]' for help on them.

/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16</error></testcase><testcase classname="tests.unit.test_camera.test_Camera" name="test_on_shutter" time="0.006"><error message="failed on setup with &quot;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 202&#10;      def test_on_shutter(self):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21&#10;  @pytest.fixture(autouse=True)&#10;  def test_cases_shortcuts(request, app, patching):&#10;file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16&#10;  @pytest.fixture()&#10;  def app(celery_app):&#10;E       fixture 'celery_app' not found&#10;&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db&#10;&gt;       use 'pytest --fixtures [testpath]' for help on them.&#10;&#10;/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16&quot;">file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/test_camera.py, line 202
      def test_on_shutter(self):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 21
  @pytest.fixture(autouse=True)
  def test_cases_shortcuts(request, app, patching):
file /home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py, line 16
  @pytest.fixture()
  def app(celery_app):
E       fixture 'celery_app' not found
&gt;       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, app, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, live_server, mailoutbox, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_app, setup_default_app_trap, test_cases_shortcuts, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db
&gt;       use 'pytest --fixtures [testpath]' for help on them.

/home/erhan/Bureaublad/django-celery-monitor/tests/unit/conftest.py:16</error></testcase></testsuite></testsuites>